---
title: ""
output: pdf_document
---


```{r knitr_settings, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}

source('../../code/functions.R')

loadLibs(c("tidyr", "dplyr", "scales", "knitr"))
```


**Table 1: Demographic Data of Training Cohort**

```{r table1, echo=FALSE, message=FALSE, warning=FALSE}

metadata <- read.csv("../../data/process/mod_metadata/metaI_final.csv", header = T, stringsAsFactors = F)
test_cohort <- read.csv("../../data/process/mod_metadata/good_metaf_final.csv", header = T, stringsAsFactors = F)

metadata <- filter(metadata, !sample %in% c(test_cohort$initial, test_cohort$followUp)) %>% 
  select(Dx_Bin, dx, Age, Gender, BMI, White) %>% mutate(Dx_Bin = gsub("adv Adenoma", "adv_adenoma", Dx_Bin), Dx_Bin = gsub("High Risk Normal", "Normal", Dx_Bin)) 

t1 <- as.data.frame(matrix(nrow = 5, ncol = 4, 
                           dimnames = 
                             list(rown = c("Dx_Bin", "Age", "Gender_f", "BMI", "White"), 
                                  coln = c("Normal", "Adenoma", "SRN", "Carcinoma"))))

data_filter1 <- c("normal", "adenoma", "adenoma", "cancer")
data_filter2 <- c("Normal", "Adenoma", "adv_adenoma", "Cancer")

# Generate the summary stats for each group
for(i in 1:length(colnames(t1))){
  
  t1["Dx_Bin", i] <- length(rownames(filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i])))
  t1["Age", i] <- filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]) %>% summarise(avg = mean(Age))
  t1["Gender_f", i] <- filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]) %>% count(Gender) %>% mutate(n = n/sum(n) * 100) %>%  filter(Gender == "f") %>% select(n)
  t1["BMI", i] <- filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]) %>% summarise(avg = mean(BMI, na.rm = TRUE))
  t1["White", i] <- length(rownames(filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i] & White == 1)))/length(rownames(filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]))) * 100 
}


# Generate SD for applicable metrics
age_sd <- c()
BMI_sd <- c()

for(i in 1:length(colnames(t1))){
  
  age_sd <- c(age_sd, (filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]) %>% summarise(std = sd(Age)))[, "std"])
  BMI_sd <- c(BMI_sd, (filter(metadata, dx == data_filter1[i] & Dx_Bin == data_filter2[i]) %>% summarise(std = sd(BMI, na.rm = TRUE)))[, "std"])
}

# Create combined table
# "u\00B1" is to add a +/- symbol where applicable

ttemptable <- as.data.frame(t(t1)) %>% mutate(Age = paste(format(Age, digits = 2, nsmall = 2), 
                                                    label = "\u00B1", 
                                                    format(age_sd, digits = 2, nmsall = 2)), 
                                        Gender_f = format(Gender_f, digits = 2, nsmall = 2), 
                                        BMI = paste(format(BMI, digits = 2, nsmall = 2), 
                                                    label = "\u00B1", 
                                                    format(BMI_sd, digits = 2, nmsall = 2)), 
                                        White = format(White, digits =2, nsmall = 2))


ft1 <- cbind(Group = c("Normal", "Adenoma", "SRN", "Carcinoma"), ttemptable$Dx_Bin, ttemptable$Age, ttemptable$Gender_f, 
             ttemptable$BMI, ttemptable$White)

age_label <- paste("Age (Mean ", label = "\u00B1", " SD)", sep = "")
bmi_label <- paste("BMI (Mean ", label = "\u00B1", " SD)", sep = "")

colnames(ft1) <- c("Group", "n", age_label, "Gender (F%)", bmi_label, "Caucasian (%)")

test <- t(ft1)
colnames(test) <- test["Group", ]
test <- test[-1, ]

kable(test, format = "markdown", align = 'c', padding = 2)

```

